/* Generated by Yosys 0.55+146 (git sha1 262b00d5e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "counter5.v:2.1-19.10" *)
module Counter_5bit(clk, count_sel, five_init, five_en, cout_down, zero_sum);
  wire _00_;
  (* force_downto = 32'd1 *)
  (* src = "counter5.v:12.25-12.37|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3 4" *)
  wire [4:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter5.v:12.25-12.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [4:0] _02_;
  (* src = "counter5.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "counter5.v:3.16-3.25" *)
  input count_sel;
  wire count_sel;
  (* src = "counter5.v:4.12-4.21" *)
  output cout_down;
  wire cout_down;
  (* src = "counter5.v:3.38-3.45" *)
  input five_en;
  wire five_en;
  (* src = "counter5.v:3.27-3.36" *)
  input five_init;
  wire five_init;
  (* src = "counter5.v:5.21-5.29" *)
  output [4:0] zero_sum;
  wire [4:0] zero_sum;
  \$lut  #(
    .LUT(4'ha),
    .WIDTH(32'd2)
  ) _03_ (
    .A({ count_sel, five_en }),
    .Y(_00_)
  );
  \$lut  #(
    .LUT(32'd1),
    .WIDTH(32'd5)
  ) _04_ (
    .A(zero_sum),
    .Y(cout_down)
  );
  \$lut  #(
    .LUT(16'hb44b),
    .WIDTH(32'd4)
  ) _05_ (
    .A({ zero_sum[1:0], five_en, count_sel }),
    .Y(_02_[1])
  );
  \$lut  #(
    .LUT(32'd18446744072602010115),
    .WIDTH(32'd5)
  ) _06_ (
    .A({ zero_sum[2], five_en, zero_sum[1:0], count_sel }),
    .Y(_02_[2])
  );
  \$lut  #(
    .LUT(64'hfe7ffefe01800101),
    .WIDTH(32'd6)
  ) _07_ (
    .A({ zero_sum[3], five_en, count_sel, zero_sum[2:0] }),
    .Y(_02_[3])
  );
  \$lut  #(
    .LUT(128'hfffe7ffffffefffe0001800000010001),
    .WIDTH(32'd7)
  ) _08_ (
    .A({ zero_sum[4], five_en, count_sel, zero_sum[3:0] }),
    .Y(_02_[4])
  );
  \$lut  #(
    .LUT(2'h1),
    .WIDTH(32'd1)
  ) _09_ (
    .A(zero_sum[0]),
    .Y(_01_[0])
  );
  (* src = "counter5.v:7.5-16.8" *)
  \$_SDFFE_PP0P_  \zero_sum_reg[0]  /* _10_ */ (
    .C(clk),
    .D(_01_[0]),
    .E(_00_),
    .Q(zero_sum[0]),
    .R(five_init)
  );
  (* src = "counter5.v:7.5-16.8" *)
  \$_SDFFE_PP0P_  \zero_sum_reg[1]  /* _11_ */ (
    .C(clk),
    .D(_02_[1]),
    .E(_00_),
    .Q(zero_sum[1]),
    .R(five_init)
  );
  (* src = "counter5.v:7.5-16.8" *)
  \$_SDFFE_PP0P_  \zero_sum_reg[2]  /* _12_ */ (
    .C(clk),
    .D(_02_[2]),
    .E(_00_),
    .Q(zero_sum[2]),
    .R(five_init)
  );
  (* src = "counter5.v:7.5-16.8" *)
  \$_SDFFE_PP0P_  \zero_sum_reg[3]  /* _13_ */ (
    .C(clk),
    .D(_02_[3]),
    .E(_00_),
    .Q(zero_sum[3]),
    .R(five_init)
  );
  (* src = "counter5.v:7.5-16.8" *)
  \$_SDFFE_PP0P_  \zero_sum_reg[4]  /* _14_ */ (
    .C(clk),
    .D(_02_[4]),
    .E(_00_),
    .Q(zero_sum[4]),
    .R(five_init)
  );
  assign _02_[0] = _01_[0];
endmodule
